version: "3.9"

services:
  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: unless-stopped
    ports:
      - "${GOACCESS_PORT}:7880"
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
    environment:
      TZ: ${TZ}
      SKIP_ARCHIVED_LOGS: ${SKIP_ARCHIVED_LOGS}
      DEBUG: ${DEBUG}
    volumes:
      - ${NPM_LOG_PATH}:/opt/log:ro
      - ${GOACCESS_DATA_PATH}:/opt/data
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
