version: "3.8"
services:
  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    restart: unless-stopped
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
    ports:
      - "5454:5454"
    volumes:
      - ~/notifiarr/config:/config
    environment:
      - TZ=America/Toronto
      - DN_API_KEY=c792e8b8-0236-4b6b-8318-9df1acb58df8
      - PUID=1000
      - PGID=1000
      - DN_UI_PASSWORD=Q6080e49#
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
