version: "3.8"

services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
    ports:
      - "${GLANCES_PORT}:61208"
    restart: unless-stopped
    command: ${GLANCES_COMMAND}
    volumes:
      - ${HOST_ROOT_PATH}:/rootfs:ro
      - ${HOST_PROC_PATH}:/host/proc:ro
      - ${HOST_ETC_PATH}:/host/etc:ro
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
