version: "3.9"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "wud.watch=false"
      - "wud.watch.digest=true"
    volumes:
      - ${CONFIG_PATH}/prowlarr/config:/config
    ports:
      - "${PRIVATE_BIND_IP:-127.0.0.1}:9696:9696"
    restart: unless-stopped
    networks:
      - arrstack

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "wud.watch=false"
      - "wud.watch.digest=true"
    volumes:
      - ${CONFIG_PATH}/sonarr/config:/config
      - ${MEDIA_PATH}/Serie:/Serie
      - ${MEDIA_PATH}/download:${MEDIA_PATH}/download
    ports:
      - "${PRIVATE_BIND_IP:-127.0.0.1}:8989:8989"
    restart: unless-stopped
    networks:
      - arrstack

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "wud.watch=false"
      - "wud.watch.digest=true"
    volumes:
      - ${CONFIG_PATH}/radarr/config:/config
      - ${MEDIA_PATH}/Movie:${MEDIA_PATH}/Movie
      - ${MEDIA_PATH}/download:${MEDIA_PATH}/download
    ports:
      - "${PRIVATE_BIND_IP:-127.0.0.1}:7878:7878"
    restart: unless-stopped
    networks:
      - arrstack

networks:
  arrstack:
    name: arrstack
    driver: bridge
