version: "3.8"

services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
    ports:
      - "${PRIVATE_BIND_IP:-127.0.0.1}:8095:8090"
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - monitoring

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /mnt/SSD1Tb:/extra-filesystems/sdb1__SSD1TB:ro
      - /mnt/Seagate3TB:/extra-filesystems/sdd2__Seagate3TB:ro
    environment:
      LISTEN: ${BESZEL_AGENT_LISTEN}
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: ${BESZEL_HUB_URL}

networks:
  monitoring:
    name: monitoring
    driver: bridge
