version: "3.9"

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    hostname: emby
    labels:
      - "wud.watch=false"
      - "wud.watch.digest=true"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - "${EMBY_HTTP_PORT}:8096"
      - "${EMBY_HTTPS_PORT}:8920"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${EMBY_CONFIG_PATH}:/config
      - ${MEDIA_MOVIES_PATH}:/media/movies
      - ${MEDIA_SERIES_PATH}:/media/series
      - ${MEDIA_MUSIC_PATH}:/media/music
      - ${EMBY_TRANSCODE_PATH}:/transcode
    restart: unless-stopped
    networks:
      - mediaapps

networks:
  mediaapps:
    name: mediaapps
    driver: bridge
